apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  namespace: gmd
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: gmd-ts
spec:
  nodeSelector:
    kubernetes.io/hostname: nitrogen
  image: typesense/typesense:30.2
  replicas: 1
  storage:
    storageClassName: local-path
    size: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: gmd
  name: gmd-ts-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: gmd-ts
  ports:
    - port: 8108
      targetPort: 8108
      name: http
    - port: 8808
      targetPort: 8808
      name: healthcheck
